name: My first Workflow

on: push 

jobs: 
    first-job:
         runs-on: ubuntu-latest
         steps: 
         - name: checkout repo
           uses: actions/checkout@v4

         - name: list of files 
           run: ls 

         - name: read the file
           run: cat README.md
          
